'use client';

import {
  Checkbox,
  Chip,
  ColorInput,
  FileInput,
  JsonInput,
  NumberInput,
  PasswordInput,
  PinInput,
  Radio,
  RangeSlider,
  Rating,
  SegmentedControl,
  Slider,
  Space,
  Switch,
  TextInput,
  Textarea,
} from '@mantine/core';
import { memo } from 'react';
import { type ControlledDemoProps } from '@/app/(home)/page';
import { Feature } from '@/components/elements/Feature';

const InputDemo = memo(function InputDemo({
  color,
  description,
  disabled,
  error,
  label,
  placeholder,
  radius,
  size,
  withAsterisk,
}: ControlledDemoProps) {
  return (
    <>
      <Feature
        group="Inputs"
        title="Checkbox"
        url="https://mantine.dev/core/checkbox/"
      >
        <Checkbox
          color={color}
          defaultChecked
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          radius={radius}
          size={size}
        />
        <Checkbox
          color={color}
          defaultChecked
          description={description}
          disabled={disabled}
          error={error}
          indeterminate
          label={label}
          radius={radius}
          size={size}
        />
        <Checkbox
          color={color}
          defaultChecked
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          labelPosition="left"
          radius={radius}
          size={size}
        />
      </Feature>

      <Feature group="Inputs" title="Chip" url="https://mantine.dev/core/chip/">
        <Chip
          color={color}
          defaultChecked
          disabled={disabled}
          radius={radius}
          size={size}
          variant="filled"
        >
          {label}
        </Chip>
        <Chip
          color={color}
          defaultChecked
          disabled={disabled}
          radius={radius}
          size={size}
          variant="light"
        >
          {label}
        </Chip>
        <Chip
          color={color}
          defaultChecked
          disabled={disabled}
          radius={radius}
          size={size}
          variant="outline"
        >
          {label}
        </Chip>
      </Feature>

      <Feature
        group="Inputs"
        title="ColorInput"
        url="https://mantine.dev/core/color-input/"
      >
        <ColorInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="default"
          withAsterisk={withAsterisk}
        />
        <ColorInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="filled"
          withAsterisk={withAsterisk}
        />
        <ColorInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="unstyled"
          withAsterisk={withAsterisk}
        />
      </Feature>

      <Feature
        group="Inputs"
        title="FileInput"
        url="https://mantine.dev/core/file-input/"
      >
        <FileInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="default"
          withAsterisk={withAsterisk}
        />
        <FileInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="filled"
          withAsterisk={withAsterisk}
        />
        <FileInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="unstyled"
          withAsterisk={withAsterisk}
        />
      </Feature>

      <Feature
        group="Inputs"
        title="JsonInput"
        url="https://mantine.dev/core/json-input/"
      >
        <JsonInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="default"
          withAsterisk={withAsterisk}
        />
        <JsonInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="filled"
          withAsterisk={withAsterisk}
        />
        <JsonInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="unstyled"
          withAsterisk={withAsterisk}
        />
      </Feature>

      <Feature
        group="Inputs"
        title="NumberInput"
        url="https://mantine.dev/core/number-input/"
      >
        <NumberInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="default"
          withAsterisk={withAsterisk}
        />
        <NumberInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="filled"
          withAsterisk={withAsterisk}
        />
        <NumberInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="unstyled"
          withAsterisk={withAsterisk}
        />
      </Feature>

      <Feature
        group="Inputs"
        title="PasswordInput"
        url="https://mantine.dev/core/password-input/"
      >
        <PasswordInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="default"
          withAsterisk={withAsterisk}
        />
        <PasswordInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="filled"
          withAsterisk={withAsterisk}
        />
        <PasswordInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="unstyled"
          withAsterisk={withAsterisk}
        />
      </Feature>

      <Feature
        group="Inputs"
        title="PinInput"
        url="https://mantine.dev/core/pin-input/"
      >
        <PinInput
          disabled={disabled}
          error={!!error}
          placeholder={placeholder || '○'}
          radius={radius}
          size={size}
          variant="default"
        />
        <PinInput
          disabled={disabled}
          error={!!error}
          placeholder={placeholder || '○'}
          radius={radius}
          size={size}
          variant="filled"
        />
        <PinInput
          disabled={disabled}
          error={!!error}
          placeholder={placeholder || '○'}
          radius={radius}
          size={size}
          variant="unstyled"
        />
      </Feature>

      <Feature
        group="Inputs"
        title="Radio"
        url="https://mantine.dev/core/radio/"
      >
        <Radio
          color={color}
          disabled={disabled}
          error={!!error}
          label={label}
          radius={radius}
          size={size}
        />
        <Radio
          color={color}
          disabled={disabled}
          error={!!error}
          label={label}
          labelPosition="left"
          radius={radius}
          size={size}
        />
      </Feature>

      <Feature
        group="Inputs"
        title="Rating"
        url="https://mantine.dev/core/rating/"
      >
        <Rating color={color} size={size} />
        <Rating color={color} highlightSelectedOnly size={size} />
        <Rating color={color} readOnly size={size} value={3} />
      </Feature>

      <Feature
        group="Inputs"
        title="SegmentedControl"
        url="https://mantine.dev/core/segmented-control/"
      >
        <SegmentedControl
          color={color}
          data={['React', 'Vue', 'Angular']}
          disabled={disabled}
          radius={radius}
          size={size}
        />
        <SegmentedControl
          color={color}
          data={['React', 'Vue', 'Angular']}
          disabled={disabled}
          orientation="vertical"
          radius={radius}
          size={size}
        />
        <SegmentedControl
          color={color}
          data={['React', 'Vue', 'Angular']}
          disabled={disabled}
          fullWidth
          radius={radius}
          size={size}
        />
        <SegmentedControl
          color={color}
          data={['React', 'Vue', 'Angular']}
          disabled={disabled}
          radius={radius}
          readOnly
          size={size}
        />
      </Feature>

      <Feature
        group="Inputs"
        title="Slider"
        url="https://mantine.dev/core/slider/"
      >
        <Slider
          color={color}
          defaultValue={20}
          disabled={disabled}
          marks={[
            { value: 20, label: '20%' },
            { value: 50, label: '50%' },
            { value: 80, label: '80%' },
          ]}
          radius={radius}
          size={size}
        />
        <Space h="xs" />
        <Slider
          color={color}
          defaultValue={80}
          disabled={disabled}
          inverted
          labelAlwaysOn
          marks={[
            { value: 20, label: '20%' },
            { value: 50, label: '50%' },
            { value: 80, label: '80%' },
          ]}
          radius={radius}
          size={size}
        />
        <Space h="xs" />
        <RangeSlider
          color={color}
          defaultValue={[20, 80]}
          disabled={disabled}
          inverted
          marks={[
            { value: 20, label: '20%' },
            { value: 50, label: '50%' },
            { value: 80, label: '80%' },
          ]}
          radius={radius}
          size={size}
        />
        <Space h="xs" />
      </Feature>

      <Feature
        group="Inputs"
        title="Switch"
        url="https://mantine.dev/core/switch/"
      >
        <Switch
          color={color}
          description={description}
          disabled={disabled}
          error={!!error}
          label={label}
          radius={radius}
          size={size}
        />
        <Switch
          color={color}
          description={description}
          disabled={disabled}
          error={!!error}
          label={label}
          labelPosition="left"
          radius={radius}
          size={size}
        />
      </Feature>

      <Feature
        group="Inputs"
        title="Textarea"
        url="https://mantine.dev/core/textarea/"
      >
        <Textarea
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="default"
          withAsterisk={withAsterisk}
        />
        <Textarea
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="filled"
          withAsterisk={withAsterisk}
        />
        <Textarea
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="unstyled"
          withAsterisk={withAsterisk}
        />
      </Feature>

      <Feature
        group="Inputs"
        title="TextInput"
        url="https://mantine.dev/core/text-input/"
      >
        <TextInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="default"
          withAsterisk={withAsterisk}
        />
        <TextInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="filled"
          withAsterisk={withAsterisk}
        />
        <TextInput
          description={description}
          disabled={disabled}
          error={error}
          label={label}
          placeholder={placeholder}
          radius={radius}
          size={size}
          variant="unstyled"
          withAsterisk={withAsterisk}
        />
      </Feature>
    </>
  );
});

export { InputDemo };
