import Document, { Html, Head, Main, NextScript } from 'next/document';

import { createGetInitialProps } from '@mantine/next';

const _getInitialProps = createGetInitialProps();

export default class _Document extends Document {
  static getInitialProps = _getInitialProps;
  render() {
    return (
      <Html>
        <Head />
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
        <link href="https://fonts.googleapis.com" rel="preconnect" />
        <link
          crossOrigin="true"
          href="https://fonts.gstatic.com"
          rel="preconnect"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow&family=Inter&family=Roboto+Slab&family=Space+Mono&display=swap"
          rel="stylesheet"
        />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
