import { Icon } from '@iconify/react';
import { ActionIcon, Button } from '@mantine/core';
import { Feature } from '@/components/ui/Feature';
import { type ControlledDemoProps } from '@/pages';

const ButtonDemo = ({
  color,
  disabled,
  label,
  radius,
  size,
}: ControlledDemoProps) => {
  return (
    <>
      <Feature title="ActionIcon">
        <ActionIcon
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="default"
        >
          <Icon
            height={24}
            icon="material-symbols:settings-outline-rounded"
            width={24}
          />
        </ActionIcon>
        <ActionIcon
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="filled"
        >
          <Icon
            height={24}
            icon="material-symbols:settings-outline-rounded"
            width={24}
          />
        </ActionIcon>
        <ActionIcon
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="light"
        >
          <Icon
            height={24}
            icon="material-symbols:settings-outline-rounded"
            width={24}
          />
        </ActionIcon>
        <ActionIcon
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="outline"
        >
          <Icon
            height={24}
            icon="material-symbols:settings-outline-rounded"
            width={24}
          />
        </ActionIcon>
        <ActionIcon
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="subtle"
        >
          <Icon
            height={24}
            icon="material-symbols:settings-outline-rounded"
            width={24}
          />
        </ActionIcon>
        <ActionIcon
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="transparent"
        >
          <Icon
            height={24}
            icon="material-symbols:settings-outline-rounded"
            width={24}
          />
        </ActionIcon>
        <ActionIcon
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="white"
        >
          <Icon
            height={24}
            icon="material-symbols:settings-outline-rounded"
            width={24}
          />
        </ActionIcon>
      </Feature>

      <Feature title="Button">
        <Button
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="default"
        >
          {label}
        </Button>
        <Button
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="filled"
        >
          {label}
        </Button>
        <Button
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="light"
        >
          {label}
        </Button>
        <Button
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="outline"
        >
          {label}
        </Button>
        <Button
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="subtle"
        >
          {label}
        </Button>
        <Button
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="transparent"
        >
          {label}
        </Button>
        <Button
          color={color}
          disabled={disabled}
          radius={radius}
          size={size}
          variant="white"
        >
          {label}
        </Button>
      </Feature>
    </>
  );
};

export { ButtonDemo };
